name: sfibai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - pillow
  - tqdm
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - imbalanced-learn
      - pyradiomics
      - SimpleITK
